# Generated by Django 2.1.7 on 2019-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='link',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ссылка'),
        ),
    ]
